### ISSUE TITLE
Changed routers and get, <could not connect to MQTT server OSError-202>

### ISSUE THREAD

**Issue by davefes** [MikeTeachman/micropython-thingspeak-mqtt-esp8266#1]
Hi Mike,

I have been running publishThingspeak.py on a ESP32 for the last few weeks without any problems.

When I changed from using a hotspot as a router to my cellphone as a hotspot I get the above error.  Do I need to get new API keys?  Does ThinkSpeak know the MAC of the router?

P.S. I have seen the word "token" used in some discussions.  Is that the issue?

Update:
I have been able to connect to a 3rd router so it seems to be a problem with the hotspot feature in my Samsung cellphone.
Do some cell providers not allow port 1883?

Thanks for putting that project up, I really appreciate the ability to get some real-time data in my off-grid situation.
Dave

**Comment by davefes** [comment]
Problem solved

# connect the device to the WiFi network
wifi = network.WLAN(network.STA_IF)
wifi.active(True)
utime.sleep(0.5)
#wifi.ifconfig(('192.168.10.80', '255.255.255.0', '192.168.10.1', '8.8.8.8'))
wifi.connect(WIFI_SSID, WIFI_PASSWORD)

I had set the first unit up with a static IP, which I didn't change when going to the following routers. The units still said that it had connected to the WiFi but having that line still in probably confused the ESP32 :(

**Comment by miketeachman** [comment]
Thanks for the followup !  That's great you found an easy fix.
